### ISSUE TITLE
Latest stable 0.3.0 doesn't launch on Ubuntu 24.04

### ISSUE THREAD

**Issue by blimbu1** [vjousse/pomodorolm#129]
## 📑 To Reproduce
1. Search For Pomodorolm
2. Double Click on the app to launch

## ☑️ Expected behavior
Double Clicking Pomodorlm should launch Pomodorlm app

## 🧑‍💻 Desktop (please complete the following information):
 - OS: Ubuntu
 - Version 24.04

## 🍅 Pomodorolm information
How did you install pomodorolm?
Installed Pomodorolm from App Center

**Comment by vjousse** [comment]
Thanks for the report @blimbu1 
Could you give me the output of `snap run pomodorolm`?

**Comment by blimbu1** [comment]
$ snap run pomodorolm
/snap/pomodorolm/50/usr/bin/pomodorolm: error while loading shared libraries: libOSSlib.so: cannot open shared object file: No such file or directory

@vjousse

**Comment by vjousse** [comment]
Ok thanks, looking into it.

**Comment by blimbu1** [comment]
Thank you @vjousse

**Comment by vjousse** [comment]
I’ve released a fix, could you give it a try @blimbu1 ?

**Comment by blimbu1** [comment]
Hi @vjousse , I have updated the app. Issue still persists. Getting the following error now.
$ snap run pomodorolm
Gtk-Message: 13:49:47.120: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (pomodorolm:53783): ERROR **: 13:49:47.208: Unable to spawn a new child process: Failed to spawn child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitNetworkProcess” (No such file or directory)
Trace/breakpoint trap (core dumped)
binay-admin@tsl00718:~$ 
binay-admin@tsl00718:~$ 
binay-admin@tsl00718:~$ snap run pomodorolm
Gtk-Message: 13:50:24.591: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

** (pomodorolm:54075): ERROR **: 13:50:24.675: Unable to spawn a new child process: Failed to spawn child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitNetworkProcess” (No such file or directory)
Trace/breakpoint trap (core dumped)

**Comment by jeffersonlipsky** [comment]
@vjousse building with docker  `docker-compose run --rm --build build-linux` and using the result executable inside `target/x86_64-unknown-linux-gnu/release` it works.

![image](https://github.com/user-attachments/assets/c4382f38-348a-45ca-8425-4a7f506bc105)

**Comment by vjousse** [comment]
Thanks for the report!
Fixed in https://github.com/vjousse/pomodorolm/commit/efa3c3f2fca3593b0dbc98a81e3169248917ae3c
